name: Build Lobby

on:
  push:
    branches:
      - 'main'
      - 'dev/*'
    paths:
      - 'apps/mopslobby/**'

jobs:
  build-plugin:
    name: build-plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up JDK 18
        uses: actions/setup-java@v3.3.0
        with:
          java-version: '18'
          distribution: 'zulu'
          cache: 'gradle'
      - name: 'Install libs and build PVP'
        run: ./gradlew build --no-daemon
      - name: 'Upload .jar artefact of plugin'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: MopsPVP Plugin JAR
          path: apps/mopslobby/target/mopslobby.jar
