name: Build Lobby

on:
  push:
    branches:
      - 'main'
      - 'dev/*'
    paths:
      - 'apps/mopslobby/**'

jobs:
  build-plugin:
    name: build-plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up JDK 18
        uses: actions/setup-java@v3.4.0
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle' 
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b    
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: MopsLobby Plugin JAR
          path: apps/mopslobby/build/libs/mopslobby-1.0-SNAPSHOT.jar
