name: Build WoolBattle

on:
  push:
    branches:
      - 'main'
      - 'dev/*'
    paths:
      - 'apps/woolbattle/**'

jobs:
  build-plugin:
    name: build-plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up JDK 18
        uses: actions/setup-java@v3.3.0
        with:
         java-version: '17'
         distribution: 'zulu'
         cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b    
      - name: Build with Gradle
        uses: gradle/gradle-build-action@e88ed3e650b26bd116cfee53cf198c1f6856682d
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: WoolBattle Plugin JAR
          path: apps/woolbattle/build/libs/woolbattle-1.0-SNAPSHOT.jar
