name: Test Dependabot branch

on:
  push:
    branches:
      - 'dependabot/*'

jobs:
  build-plugins:
    name: build-plugins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Set up JDK 17
        uses: actions/setup-java@v3.1.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: 'Install libs and build plugins'
        run: mvn install --projects :mopsbase,:mopselements,:mopspvps,:mopslobby,:woolbattle
      - name: 'Move .jar s'
        run: |
          mkdir staging
          cp apps/mopspvps/target/*.jar staging
          cp apps/woolbattle/target/*.jar staging
          cp apps/mopslobby/target/*.jar staging
          cp libs/mopsbase/target/*.jar staging
          cp libs/mopselements/target/*.jar staging
      - name: 'Upload .jar artefact of plugin'
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Mops Plugins .jar
          path: staging/
